package daviplata.nacional.iOS.pageObjects;

import net.serenitybdd.core.pages.PageObject;

public class MeterPlataPageObjects extends PageObject {
	
	public static final String BOTON_METER_PLATA = "//XCUIElementTypeStaticText[@name='Meter plata'] | //XCUIElementTypeOther[contains(@name,'btn-my-movements-0') or contains(@name, 'Meter Plata botón')]";
	public static final String BOTON_METER_PLATA_MH = "//XCUIElementTypeStaticText[@name='Meter Plata']";
	public static final String BOTON_MENU_HAMBURGUESA = "//*[@name='Menú DaviPlata botón']";
	public static final String BOTON_USAR_PLATA_MH = "//*[@value='Usar Plata']";
	public static final String BOTON_METER_PLATA_HOME = "//XCUIElementTypeOther[contains(@name,'btn-my-movements-0') or contains(@name, 'Meter Plata botón')] | //XCUIElementTypeStaticText[@name='Meter plata'] | //XCUIElementTypeOther[contains(@name,'btn-my-movements-0') or contains(@name, 'Meter Plata botón')]";	
	public static final String TXT_DESDE_DONDE_METER_PLATA = "//*[@name='Seleccione desde dónde quiere Meter Plata']";
	public static final String BOTON_REGRESO_HOME = "//*[@name='atrás Botón']";
	public static final String TXT_DESDE_DONDE_METER_PLATA_HM = "//*[@name='Seleccione desde dónde quiere Meter Plata']";
	public static final String BTN_METER_PLATA_DESDE_CUALQUIER_BANCO = "//*[@name='Desde cualquier banco']";	
	public static final String FORM_DATOS_METER_PLATA = "//*[@name='Complete los datos para Meter Plata a DaviPlata']";	
	public static final String BTN_REGRESO_DONDE_METER_PLATA = "//*[@name='Atras']";
	public static final String BTN_METER_PLATA_EN_EFECTIVO = "//*[@name='En efectivo']";
	public static final String MENSAJE_POP_UP = "//XCUIElementTypeStaticText[contains(@name,'Está llegando al tope mensual')]";
	public static final String BTN_REGRESO_MODULO_DONDE_METER_PLATA = "//*[@name='icon back button'] | //XCUIElementTypeButton[contains(@name,'Atras')] | //XCUIElementTypeButton[contains(@name, 'Regresar')] | //XCUIElementTypeButton[contains(@label, 'Regresar')] | //XCUIElementTypeButton[contains(@name, 'Botón atrás')] | //XCUIElementTypeButton[contains(@name,'Botón atrás')] | //*[contains(@name,'ic arrow left')] | //*[contains(@name, 'Regresar')] | //XCUIElementTypeButton[contains(@name, 'icon back button')] | //XCUIElementTypeOther[@name='image-header-0']/XCUIElementTypeImage | //XCUIElementTypeButton[@name='Atrás Botón']";
	public static final String CAMPO_INGRESO_NUMERO_CEL = "//XCUIElementTypeTextField[contains(@name, 'A qué número quiere meter plata')]";
	public static final String CAMPO_CONFIRMACION_INGRESO_NUMERO_CEL = "//XCUIElementTypeTextField[contains(@name, 'Confirme el número al que quiere meter plata')]";
	public static final String POP_UP_METER_PLATA_EFECTIVO = "//*[@name='¿Cómo Meter Plata en Efectivo?']";
	public static final String BTN_POP_UP_ENCONTRAR = "//*[@name='Encontrar botón']";
	public static final String TXT_NUM_CEL_DEBE_INICIAR_CON_TRES = "//*[@name='El número debe iniciar con el digito 3']";
	public static final String CAMPO_CONFIRME_NUMERO_CEL = "//XCUIElementTypeTextField[contains(@name, 'Confirme el número al que quiere meter plata')]";
	public static final String TXT_NUM_CEL_CONFIRMACION_DEBE_INICIAR_CON_TRES = "//*[@name='El número debe iniciar con el digito 3']";
	public static final String TEXTO_A_QUE_NUMERO_QUIERE_METER_PLATA = "//XCUIElementTypeStaticText[contains(@name,'A qué número quiere meter')]";
	public static final String TEXTO_CONFIRMAR_NUMERO_QUIERE_METER_PLATA = "//XCUIElementTypeStaticText[contains(@name,'Confirme el número')]";
	public static final String TEXTO_CUANTA_PLATA_QUIERE_METER = "//XCUIElementTypeStaticText[contains(@name,'Cuánta plata quiere meter')]";
	public static final String TEXTO_DESDE_QUE_BANCO_QUIERE_METER_PLATA = "//XCUIElementTypeStaticText[contains(@name,'Desde qué banco')]";
	public static final String TEXTO_INGRESE_CORREO_METER_PLATA = "//XCUIElementTypeStaticText[contains(@name,'Ingrese su correo')]";
	public static final String INPUT_NUMERO_CONFIRMACION_DESDE_OTROS_BANCOS = "//*[@value='Confirme el número de DaviPlata']";
	public static final String INPUT_NUMERO_CONFIRMACION = "//XCUIElementTypeTextField[contains(@name, 'A qué número quiere meter plata')]";
	public static final String TEXTO_METER_PLATA_EFECTIVO = "//XCUIElementTypeButton[@name='Pagar y Meter Plata']";
	public static final String TEXTO_MENSAJE_NO_COINCIDE = "//XCUIElementTypeStaticText[@name='Los números no coinciden']";
	public static final String INPUT_MONTO = "(//XCUIElementTypeStaticText[@name='$']//following-sibling::XCUIElementTypeTextField)[1]";
	public static final String TEXTO_MAXIMO_MINIMO_SALDO = "//XCUIElementTypeStaticText[contains(@name,'El valor mínimo por')]";
	public static final String BOTON_SELECCIONE_EL_BANCO = "//XCUIElementTypeStaticText[@name='Seleccione el banco']";
	public static final String LISTA_BANCOS = "//XCUIElementTypeStaticText[contains(@name,'Seleccione el banco')]/parent::XCUIElementTypeOther/following-sibling::XCUIElementTypeOther/XCUIElementTypeOther";
	public static final String OPCIONES_LISTA_BANCOS = "(//XCUIElementTypeStaticText[normalize-space(@name) != ''])[position() >= 12 and position() <= 58]";
	public static final String INPUT_CORREO = "(//XCUIElementTypeTextField)[4] | //XCUIElementTypeStaticText[@name='Ingrese su correo registrado en PSE']";
	public static final String OPCION_BANCO_ALIANZA_FIDUCIARIA = "//XCUIElementTypeStaticText[@name='ALIANZA FIDUCIARIA']";
	public static final String OPCION_DESDE_CUENTAS_DAVIVIENDA = "//XCUIElementTypeStaticText[contains(@name,'Desde cuentas Davivienda')]";
	public static final String TEXTO_FORMULARIO_PSE = "//XCUIElementTypeStaticText[contains(@value,'Complete la información')]";
	public static final String INPUT_CORREO_PSE = "//XCUIElementTypeTextField[contains(@name,'Ingrese su correo registrado en PSE')]";
	public static final String INPUT_INGRESE_UN_VALOR = "//XCUIElementTypeTextField[contains(@name,'¿Cuánta plata quiere meter?')] | //XCUIElementTypeTextField[@name='¿Cuánta plata quiere meter?']";
	public static final String INPUT_INGRESE_UN_NUMERO = "//XCUIElementTypeTextField[@name='¿A qué número quiere meter plata?']";
	public static final String BOTON_CONTINUAR = "//XCUIElementTypeButton[contains(@name,'Continuar')] | //XCUIElementTypeButton[label='Continuar']";
	public static final String BTN_FINALIZAR = "//XCUIElementTypeButton[@name='Finalizar']";
	public static final String BOTON_CONTINUAR_VERIFICAR_INFO = "//XCUIElementTypeButton[@name='Continuar']";
	public static final String TEXTO_INFORMACION_INGRESADA = "//XCUIElementTypeStaticText[@name='El valor a cargar en DaviPlata se descontará del banco Davivienda a través de PSE']";
	public static final String BOTON_REGRESAR_FORMULARIO = "//*[@name='icon back button'] | //XCUIElementTypeButton[contains(@name,'Atras')] | //XCUIElementTypeButton[contains(@name, 'Regresar')] | //XCUIElementTypeButton[contains(@label, 'Regresar')] | //XCUIElementTypeButton[contains(@name, 'Botón atrás')] | //XCUIElementTypeButton[contains(@name,'Botón atrás')] | //*[contains(@name,'ic arrow left')] | //*[contains(@name, 'Regresar')] | //XCUIElementTypeButton[contains(@name, 'icon back button')] | //XCUIElementTypeOther[@name='image-header-0']/XCUIElementTypeImage | //XCUIElementTypeButton[@name='Atrás Botón']";
	public static final String BOTON_NECESITO_AYUDA = "(//XCUIElementTypeOther[contains(@label, 'Ayuda')])[8] | //XCUIElementTypeOther[@name='btn-rigth-1'] | //XCUIElementTypeOther[contains(@name,'Ir a asesor virtual boton')]";
	public static final String BOTON_CERRAR_DAVIPLATA = "//XCUIElementTypeButton[contains(@name,'Cerrar DaviPlata')]";
	public static final String TEXTO_POP_UP_CERRAR_DAVIPLATA = "//XCUIElementTypeStaticText[contains(@name,'Está seguro que desea salir')]";
	public static final String BOTON_CANCELAR_POP_UP_CERRAR_DAVIPLATA = "//XCUIElementTypeButton[@name='Cancelar']";
	public static final String BOTON_ACEPTAR_POP_UP_ACEPTAR_DAVIPLATA = "//XCUIElementTypeButton[@name='Aceptar']";
	public static final String TEXTO_INGRESE_A_SU_DAVIPLATA = "//XCUIElementTypeStaticText[contains(@name,'Ingrese a su Daviplata')]";
	public static final String OPCION_BANCO_UNION_COLOMBIANO = "//XCUIElementTypeStaticText[@name='BANCO UNION COLOMBIANO']";
	public static final String TEXTO_COSTO_TRANSACCION = "(//XCUIElementTypeStaticText[contains(@name,'$')])[2] | (//XCUIElementTypeStaticText[contains(@name,'$')])[2]";
	public static final String CHECK_SWITCH_TRATAMIENTO_DATOS = "(//XCUIElementTypeSwitch)[1]";
	public static final String CHECK_SWITCH_TYC = "(//XCUIElementTypeSwitch)[2]";
	public static final String TEXTO_AUTORIZA_PSE = "//XCUIElementTypeStaticText[contains(@name,'Autoriza a PSE')]";
	public static final String LOGO_PSE = "//XCUIElementTypeOther[@name='Banco Sample Crédito']/XCUIElementTypeOther/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]";
	public static final String TXT_WELCOME_PSE = "//XCUIElementTypeStaticText[contains(@name, 'Wellcome to PSE')]";
	public static final String INPUT_ACCOUNT_AGENCY = "//XCUIElementTypeTextField[@name='Format: 4 digits']";
	public static final String INPUT_ACCOUNT_NUMBER = "//XCUIElementTypeTextField[@name='Format: 4-6 digits']";
	public static final String INPUT_PASSWORD = "//XCUIElementTypeSecureTextField[@name='Format: 6 digits']";
    public static final String BTN_DONE = "//XCUIElementTypeButton[@name='Done']";
	public static final String BOTON_PAY = "//XCUIElementTypeButton[@name='Pay']";
	public static final String TEXTO_TRANSACCION_EXITOSA = "//XCUIElementTypeStaticText[contains(@name,'Transacción')] | //XCUIElementTypeStaticText[contains(@name,'exitosa')]";
	public static final String CAMPO_FECHA_Y_HORA = "//XCUIElementTypeStaticText[@name='Fecha y hora de la transacción']";
	public static final String CAMPO_NUMERO_PRODUCTO_DESTINO = "//XCUIElementTypeStaticText[@name='Número al que metió plata']";
	public static final String CAMPO_CUANTA_PLATA_METIO = "//XCUIElementTypeStaticText[@name='¿Cuánta plata metió?']";
	public static final String CAMPO_NUMERO_AUTORIZACIÓN = "//XCUIElementTypeStaticText[@name='Número de autorización']";
	public static final String BOTON_FINALIZAR = "//XCUIElementTypeButton[contains(@name,'Finalizar')] | //XCUIElementTypeButton[@name='Finalizar']";
	public static final String BOTON_METER_PLATA_VERIFIQUE_INFORMACION = "//XCUIElementTypeButton[@name='Meter Plata']";
	public static final String MENSAJE_TRANSACCION_NO_EXITOSA = "//XCUIElementTypeStaticText[contains(@name, 'El DaviPlata destino')] | //XCUIElementTypeStaticText[contains(@name, 'no puede')] | //XCUIElementTypeStaticText[contains(@name, 'no permite')] | //XCUIElementTypeStaticText[@name='Transacción no exitosa'] | //XCUIElementTypeStaticText[contains(@name, 'no exitosa')]";
	public static final String BOTON_COMPARTIR_TRANSACCION = "//XCUIElementTypeButton[@name='Compartir Botón']";
	public static final String LISTA_DESPLEGABLE_BANCOS = "//XCUIElementTypeStaticText[@name='Seleccione el banco'] | //XCUIElementTypeOther[contains(@name, 'Desde qué banco quiere')]/following-sibling::XCUIElementTypeOther";
	public static final String POPUP_COMUNICACION_NO_DISPONIBLE = "//XCUIElementTypeStaticText[contains(@name, 'Comunicación no disponible')]";
	public static final String POPUP_RECHAZO_TRANSACCION = "//XCUIElementTypeStaticText[contains(@name, 'DaviPlata destino no permite')]";
}
